### ISSUE TITLE
ST_TOPIC_PRIVATE_CATEGORY_PK setting does not matches the private category

### ISSUE THREAD

**Issue by karrozia** [sirex/ubuntu.lt#8]
Applying spirit_category.0002_auto_20150728_0442...
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/home/karrozia/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/home/karrozia/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/karrozia/venv/lib/python3.5/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/karrozia/venv/lib/python3.5/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/home/karrozia/venv/lib/python3.5/site-packages/spirit/core/management/commands/spiritinstall.py", line 14, in handle
    call_command('migrate', stdout=self.stdout, stderr=self.stderr)
  File "/home/karrozia/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 120, in call_command
    return command.execute(*args, **defaults)
  File "/home/karrozia/venv/lib/python3.5/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/home/karrozia/venv/lib/python3.5/site-packages/django/core/management/commands/migrate.py", line 222, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/home/karrozia/venv/lib/python3.5/site-packages/django/db/migrations/executor.py", line 110, in migrate
    self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
  File "/home/karrozia/venv/lib/python3.5/site-packages/django/db/migrations/executor.py", line 148, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/karrozia/venv/lib/python3.5/site-packages/django/db/migrations/migration.py", line 115, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/karrozia/venv/lib/python3.5/site-packages/django/db/migrations/operations/special.py", line 183, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/home/karrozia/venv/lib/python3.5/site-packages/spirit/category/migrations/0002_auto_20150728_0442.py", line 25, in default_categories
    pk=private_category.pk))
ValueError: ST_TOPIC_PRIVATE_CATEGORY_PK setting does not matches the private category. The expected value was: 3

**Comment by sirex** [comment]
Related to https://github.com/nitely/Spirit/issues/94
